chr <- read.csv("stacked.txt", header = TRUE, row.names = 1, sep = "\t")
library(RColorBrewer)
#sequential <- brewer.pal(2, "PuRd")
colors <- c("blue", "red")
pdf("stacked.pdf", width = 10, height = 10)
#barplot(t(as.matrix(chr)), col = sequential, xlab = "Chromosome", ylab = "Methylation/Mb")
barplot(t(as.matrix(chr)), col = colors, xlab = "Chromosome", ylab = "Methylation/Mb")
#legend("topright", legend = c("Hypermethylation", "Hypomethylation"),fill = sequential[2:1], title = "Direction")
legend("topright", legend = c("Hypomethylation", "Hypermethylation"), fill = colors, title = "Direction")
dev.off()
